/*
 * MBX, Community Based Project
 * Copyright (c) 2024 SiriusB_
 * SPDX-License-Identifier: MIT
 */

export const defaultSelectedPerMap: Record<string, string[]> = {
    spawn: [
        "log_coconuts",
        "log_banana",
        "lily",
        "clover",
        "ore_coal",
        "ore_copper",
        "ore_iron",
        "ore_lapis_lazuli",
        "ore_gold",
        "ore_emerald",
        "ore_redstone",
        "ore_diamond",
        "ore_silver",
        "blue_heartvine",
        "red_heartvine",
        "yellow_heartvine",
        "spawn_fish",
        "spawn_bloon",
        "spawn_viewPoint",
    ],
    home_island: [
        "treasure_common",
        "treasure_uncommon",
        "treasure_rare",
        "treasure_epic",
        "treasure_legendary",
        "treasure_mythic",
    ],
    nether_island: ["treasure_rare", "treasure_epic", "treasure_legendary"],
    end_island: ["treasure_epic", "treasure_legendary", "treasure_mythic"],
    kokoko: [
        "log_coconuts",
        "log_banana",
        "lily",
        "clover",
        "ore_silver",
        "ore_ashstone",
        "belladonna",
        "log_mahogany",
        "ore_bauxite",
        "log_dark_coconut",
        "hemlock",
        "mandrake",
        "log_sacred_coconut",
        "kokoko_fish_deepshoal",
        "kokoko_fish_coralshoal",
        "kokoko_fish_jungleshoal",
        "kokoko_bloon",
        "kokoko_viewPoint",
    ],
    quadra_plains: [
        "log_chestnut",
        "log_walnut",
        "log_mystic_horbeam",
        "chamomille",
        "henbane",
        "peppermint",
        "echinacea",
        "ore_dolomite",
        "ore_cobalt",
        "ore_raw_obsidian",
        "ore_rainbow",
        "quadra_plains_fish_plainshoal",
        "quadra_plains_fish_swampshoal",
        "quadra_plains_bloon",
        "quadra_plains_viewPoint",
    ],
    bamboo_peak: [
        "log_ecalyptus",
        "log_laughing",
        "log_elm",
        "st_john_wort",
        "ginger_root",
        "origami",
        "ore_manganese",
        "ore_liquid_diamond",
        "bamboo_peak_fish",
        "bamboo_peak_bloon",
        "bamboo_peak_viewPoint",
    ],
    frostbite_fortress: [
        "log_hazel",
        "log_maple",
        "log_yew",
        "ore_tin",
        "ore_opale",
        "mullein",
        "foxglove",
        "yarrow",
        "snowdrop",
        "five_leaf_clover",
        "frostbite_fortress_fish",
        "frostbite_fortress_bloon",
        "frostbite_fortress_viewPoint",
    ],
    sandwhisper_dunes: [
        "log_olive",
        "ore_seafoam",
        "ore_silicate",
        "ore_topaz",
        "sandwhisper_dunes_fish",
        "sandwhisper_dunes_bloon",
        "sandwhisper_dunes_viewPoint",
    ],
};
