/*
 * MBX, Community Based Project
 * Copyright (c) 2024 SiriusB_
 * SPDX-License-Identifier: MIT
 */

type FishRarity =
    | "fishing.rarity.vanilla"
    | "fishing.rarity.common"
    | "fishing.rarity.uncommon"
    | "fishing.rarity.rare"
    | "fishing.rarity.epic"
    | "fishing.rarity.legendary"
    | "fishing.rarity.mythic";

type FishTime =
    | "fishing.time.day"
    | "fishing.time.night"
    | "fishing.time.day_night"
    | string;

export interface FishInfo {
    name: string;
    level: number;
    time: FishTime[];
    rarity: FishRarity;
    image?: string;
    condition?: string;
}

export const mapNameTranslationKeys: Record<string, string> = {
    spawn: "mappage.maps.spawn_island.name",
    kokoko: "mappage.maps.kokoko_island.name",
    quadra_plains: "mappage.maps.quadra_plains.name",
    bamboo_peak: "mappage.maps.bamboo_peak.name",
    frostbite_fortress: "mappage.maps.frostbite_fortress.name",
    sandwhisper_dunes: "mappage.maps.sandwhisper_dunes.name",
};

export const spotNames: Record<string, string> = {
    tropical_shoal: "fishing.spot.tropical_shoal",
    deep_shoal: "fishing.spot.deep_shoal",
    coral_shoal: "fishing.spot.coral_shoal",
    jungle_shoal: "fishing.spot.jungle_shoal",
    plain_shoal: "fishing.spot.plain_shoal",
    swamp_shoal: "fishing.spot.swamp_shoal",
    bamboo_shoal: "fishing.spot.bamboo_shoal",
    bamboo_jungle_shoal: "fishing.spot.bamboo_jungle_shoal",
    cold_shoal: "fishing.spot.cold_shoal",
    superdeep_shoal: "fishing.spot.superdeep_shoal",
    desert_shoal: "fishing.spot.desert_shoal",
    canyon_shoal: "fishing.spot.canyon_shoal",
};

export const fishData: Record<string, Record<string, FishInfo[]>> = {
    spawn: {
        tropical_shoal: [
            {
                name: "fishing.common_treasure",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.common",
                condition: "",
                image: "assets/media/item/fishing/treasure_common.png",
            },
            {
                name: "fishing.common_key",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.common",
                condition: "",
                image: "assets/media/item/fishing/key_common.png",
            },
            {
                name: "fishing.mandarinfish",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.common",
                condition: "",
                image: "assets/media/item/fishing/mandarinfish.png",
            },
            {
                name: "fishing.sea_salt",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.uncommon",
                condition: "",
                image: "assets/media/item/fishing/sea_salt.png",
            },
            {
                name: "fishing.pirate_crab",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.uncommon",
                condition: "",
                image: "assets/media/item/fishing/pirate_crab.png",
            },
            {
                name: "fishing.cowrie_shell",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.uncommon",
                condition: "",
                image: "assets/media/item/fishing/cowrie_shell.png",
            },
            {
                name: "fishing.kraken",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.uncommon",
                condition: "",
                image: "assets/media/item/fishing/kraken.png",
            },
            {
                name: "fishing.breaded_fish",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.common",
                condition: "",
                image: "assets/media/item/fishing/breaded_fish.png",
            },
            {
                name: "fishing.bone",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.vanilla",
                condition: "",
                image: "assets/media/item/fishing/bone.png",
            },
            {
                name: "fishing.algae",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.vanilla",
                condition: "",
                image: "assets/media/item/fishing/kelp.png",
            },
            {
                name: "fishing.clam",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.rare",
                condition: "",
                image: "assets/media/item/fishing/clam.png",
            },
        ],
    },
    kokoko: {
        deep_shoal: [
            {
                name: "fishing.common_key",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.common",
                condition: "",
                image: "assets/media/item/fishing/key_common.png",
            },
            {
                name: "fishing.tuna",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.uncommon",
                condition: "",
                image: "assets/media/item/fishing/tuna_fish.png",
            },
            {
                name: "fishing.green_ray",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.uncommon",
                condition: "",
                image: "assets/media/item/fishing/green_ray.png",
            },
            {
                name: "fishing.pirate_crab",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.uncommon",
                condition: "",
                image: "assets/media/item/fishing/pirate_crab.png",
            },
            {
                name: "fishing.kraken",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.uncommon",
                condition: "",
                image: "assets/media/item/fishing/kraken.png",
            },
            {
                name: "fishing.sea_salt",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.uncommon",
                condition: "",
                image: "assets/media/item/fishing/sea_salt.png",
            },
            {
                name: "fishing.cowrie_shell",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.uncommon",
                condition: "",
                image: "assets/media/item/fishing/cowrie_shell.png",
            },
            {
                name: "fishing.clam",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.rare",
                condition: "",
                image: "assets/media/item/fishing/clam.png",
            },
            {
                name: "fishing.moon_jellyfish",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.legendary",
                condition: "",
                image: "assets/media/item/fishing/moon_jellyfish.png",
            },
            {
                name: "fishing.ink_sac",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.vanilla",
                condition: "",
                image: "assets/media/item/fishing/ink_sac.png",
            },
            {
                name: "fishing.bone",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.vanilla",
                condition: "",
                image: "assets/media/item/fishing/bone.png",
            },
            {
                name: "fishing.common_treasure",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.common",
                condition: "",
                image: "assets/media/item/fishing/treasure_common.png",
            },
        ],
        coral_shoal: [
            {
                name: "fishing.uncommon_key",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.uncommon",
                condition: "",
                image: "assets/media/item/fishing/key_uncommon.png",
            },
            {
                name: "fishing.uncommon_treasure",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.uncommon",
                condition: "",
                image: "assets/media/item/fishing/treasure_uncommon.png",
            },
            {
                name: "fishing.sea_salt",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.uncommon",
                condition: "",
                image: "assets/media/item/fishing/sea_salt.png",
            },
            {
                name: "fishing.lionfish",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.epic",
                condition: "",
                image: "assets/media/item/fishing/lionfish.png",
            },
            {
                name: "fishing.parrotfish",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.rare",
                condition: "",
                image: "assets/media/item/fishing/parrotfish.png",
            },
            {
                name: "fishing.moorish_idol",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.rare",
                condition: "",
                image: "assets/media/item/fishing/moorish_idol.png",
            },
            {
                name: "fishing.octopus",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.legendary",
                condition: "",
                image: "assets/media/item/fishing/octopus.png",
            },
            {
                name: "fishing.reef_shark",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.epic",
                condition: "",
                image: "assets/media/item/fishing/reef_shark.png",
            },
            {
                name: "fishing.tube_coral",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.vanilla",
                condition: "",
                image: "assets/media/item/fishing/tube_coral.png",
            },
            {
                name: "fishing.bubble_coral",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.vanilla",
                condition: "",
                image: "assets/media/item/fishing/bubble_coral.png",
            },
        ],
        jungle_shoal: [
            {
                name: "fishing.rare_key",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.rare",
                condition: "",
                image: "assets/media/item/fishing/key_rare.png",
            },
            {
                name: "fishing.rare_treasure",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.rare",
                condition: "",
                image: "assets/media/item/fishing/treasure_rare.png",
            },
            {
                name: "fishing.pirate_crab",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.uncommon",
                condition: "",
                image: "assets/media/item/fishing/pirate_crab.png",
            },
            {
                name: "fishing.barracuda",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.legendary",
                condition: "",
                image: "assets/media/item/fishing/barracuda.png",
            },
            {
                name: "fishing.cowrie_shell",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.uncommon",
                condition: "",
                image: "assets/media/item/fishing/cowrie_shell.png",
            },
            {
                name: "fishing.lobster",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.mythic",
                condition: "",
                image: "assets/media/item/fishing/lobster.png",
            },
            {
                name: "fishing.flying_fish",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.legendary",
                condition: "",
                image: "assets/media/item/fishing/flying_fish.png",
            },
            {
                name: "fishing.sea_salt",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.uncommon",
                condition: "",
                image: "assets/media/item/fishing/sea_salt.png",
            },
            {
                name: "fishing.bone",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.vanilla",
                condition: "",
                image: "assets/media/item/fishing/bone.png",
            },
        ],
    },
    quadra_plains: {
        plain_shoal: [
            {
                name: "fishing.common_treasure",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.common",
                condition: "",
                image: "assets/media/item/fishing/treasure_common.png",
            },
            {
                name: "fishing.common_key",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.common",
                condition: "",
                image: "assets/media/item/fishing/key_common.png",
            },
            {
                name: "fishing.wrasse",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.rare",
                condition: "",
                image: "assets/media/item/fishing/wrasse.png",
            },
            {
                name: "fishing.angelfish",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.common",
                condition: "",
                image: "assets/media/item/fishing/angelfish.png",
            },
            {
                name: "fishing.swordfish",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.uncommon",
                condition: "",
                image: "assets/media/item/fishing/swordfish.png",
            },
            {
                name: "fishing.rainbow_trout",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.rare",
                condition: "",
                image: "assets/media/item/fishing/rainbow_trout.png",
            },
            {
                name: "fishing.ink_sac",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.vanilla",
                condition: "",
                image: "assets/media/item/fishing/ink_sac.png",
            },
            {
                name: "fishing.bone",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.vanilla",
                condition: "",
                image: "assets/media/item/fishing/bone.png",
            },
        ],
        swamp_shoal: [
            {
                name: "fishing.uncommon_key",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.uncommon",
                condition: "",
                image: "assets/media/item/fishing/key_uncommon.png",
            },
            {
                name: "fishing.uncommon_treasure",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.uncommon",
                condition: "",
                image: "assets/media/item/fishing/treasure_uncommon.png",
            },
            {
                name: "fishing.poop",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.rare",
                condition: "",
                image: "assets/media/item/fishing/poop.png",
            },
            {
                name: "fishing.carp",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.rare",
                condition: "",
                image: "assets/media/item/fishing/fish_carp.png",
            },
            {
                name: "fishing.goby",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.epic",
                condition: "",
                image: "assets/media/item/fishing/goby.png",
            },
            {
                name: "fishing.rainbow_trout",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.rare",
                condition: "",
                image: "assets/media/item/fishing/rainbow_trout.png",
            },
            {
                name: "fishing.electric_eel",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.legendary",
                condition: "",
                image: "assets/media/item/fishing/fish_electric_eel.png",
            },
        ],
    },
    bamboo_peak: {
        bamboo_shoal: [
            {
                name: "fishing.sea_pickle",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.vanilla",
                condition: "",
                image: "assets/media/item/fishing/sea_pickle.png",
            },
            {
                name: "fishing.bamboo",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.vanilla",
                condition: "",
                image: "assets/media/item/fishing/bamboo.png",
            },
            {
                name: "fishing.common_treasure",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.common",
                condition: "",
                image: "assets/media/item/fishing/treasure_common.png",
            },
            {
                name: "fishing.common_key",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.common",
                condition: "",
                image: "assets/media/item/fishing/key_common.png",
            },
            {
                name: "fishing.surgeonfish",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.rare",
                condition: "",
                image: "assets/media/item/fishing/surgeonfish.png",
            },
            {
                name: "fishing.clownfish",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.uncommon",
                condition: "",
                image: "assets/media/item/fishing/clownfish.png",
            },
            {
                name: "fishing.monkfish",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.epic",
                condition: "",
                image: "assets/media/item/fishing/monkfish.png",
            },
            {
                name: "fishing.goldfish",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.rare",
                condition: "",
                image: "assets/media/item/fishing/goldfish.png",
            },
        ],
        bamboo_jungle_shoal: [
            {
                name: "fishing.blue_tang",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.epic",
                condition: "",
                image: "assets/media/item/fishing/blue_tang.png",
            },
            {
                name: "fishing.piranha",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.rare",
                condition: "",
                image: "assets/media/item/fishing/piranha.png",
            },
            {
                name: "fishing.frogfish",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.legendary",
                condition: "",
                image: "assets/media/item/fishing/frogfish.png",
            },
            {
                name: "fishing.sushi_crab",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.legendary",
                condition: "",
                image: "assets/media/item/fishing/sushi_crab.png",
            },
            {
                name: "fishing.uncommon_treasure",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.uncommon",
                condition: "",
                image: "assets/media/item/fishing/treasure_uncommon.png",
            },
            {
                name: "fishing.uncommon_key",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.uncommon",
                condition: "",
                image: "assets/media/item/fishing/key_uncommon.png",
            },
            {
                name: "fishing.sea_pickle",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.vanilla",
                condition: "",
                image: "assets/media/item/fishing/sea_pickle.png",
            },
            {
                name: "fishing.bamboo",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.vanilla",
                condition: "",
                image: "assets/media/item/fishing/bamboo.png",
            },
        ],
    },
    frostbite_fortress: {
        cold_shoal: [
            {
                name: "fishing.nether_star",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.vanilla",
                condition: "",
                image: "assets/media/item/fishing/nether_star.png",
            },
            {
                name: "fishing.uncommon_treasure",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.uncommon",
                condition: "",
                image: "assets/media/item/fishing/treasure_uncommon.png",
            },
            {
                name: "fishing.uncommon_key",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.uncommon",
                condition: "",
                image: "assets/media/item/fishing/key_uncommon.png",
            },
            {
                name: "fishing.sea_salt",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.uncommon",
                condition: "",
                image: "assets/media/item/fishing/sea_salt.png",
            },
            {
                name: "fishing.snow_crab",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.epic",
                condition: "",
                image: "assets/media/item/fishing/snow_crab.png",
            },
            {
                name: "fishing.shrimp",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.epic",
                condition: "",
                image: "assets/media/item/fishing/shrimp.png",
            },
            {
                name: "fishing.zander",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.epic",
                condition: "",
                image: "assets/media/item/fishing/zander.png",
            },
            {
                name: "fishing.golden_shrimp",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.legendary",
                condition: "",
                image: "assets/media/item/fishing/golden_shrimp.png",
            },
            {
                name: "fishing.ice",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.vanilla",
                condition: "",
                image: "assets/media/item/fishing/ice.png",
            },
            {
                name: "fishing.prismarine_shard",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.vanilla",
                condition: "",
                image: "assets/media/item/fishing/prismarine_shard.png",
            },
        ],
        superdeep_shoal: [
            {
                name: "fishing.ink_sac",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.vanilla",
                condition: "",
                image: "assets/media/item/fishing/ink_sac.png",
            },
            {
                name: "fishing.common_key",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.common",
                condition: "",
                image: "assets/media/item/fishing/key_common.png",
            },
            {
                name: "fishing.common_treasure",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.common",
                condition: "",
                image: "assets/media/item/fishing/treasure_common.png",
            },
            {
                name: "fishing.rare_key",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.rare",
                condition: "",
                image: "assets/media/item/fishing/key_rare.png",
            },
            {
                name: "fishing.rare_treasure",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.rare",
                condition: "",
                image: "assets/media/item/fishing/treasure_rare.png",
            },
            {
                name: "fishing.kraken",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.uncommon",
                condition: "",
                image: "assets/media/item/fishing/kraken.png",
            },
            {
                name: "fishing.blob_fish",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.mythic",
                condition: "",
                image: "assets/media/item/fishing/blobfish.png",
            },
            {
                name: "fishing.nautilus",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.mythic",
                condition: "",
                image: "assets/media/item/fishing/nautilus.png",
            },
            {
                name: "fishing.john_dory",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.legendary",
                condition: "",
                image: "assets/media/item/fishing/john_dory.png",
            },
            {
                name: "fishing.haddock",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.epic",
                condition: "",
                image: "assets/media/item/fishing/haddock.png",
            },
        ],
    },
    sandwhisper_dunes: {
        desert_shoal: [
            {
                name: "fishing.rainbow_sparkle_jelly",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.legendary",
                condition: "",
                image: "assets/media/item/fishing/rainbow_sparkle_jelly.png",
            },
            {
                name: "fishing.uncommon_treasure",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.uncommon",
                condition: "",
                image: "assets/media/item/fishing/treasure_uncommon.png",
            },
            {
                name: "fishing.butterflyfish",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.rare",
                condition: "",
                image: "assets/media/item/fishing/butterflyfish.png",
            },
            {
                name: "fishing.triggerfish",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.rare",
                condition: "",
                image: "assets/media/item/fishing/triggerfish.png",
            },
            {
                name: "fishing.anchovy",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.common",
                condition: "",
                image: "assets/media/item/fishing/anchovy.png",
            },
            {
                name: "fishing.uncommon_key",
                level: 0,
                time: ["fishing.time.night"],
                rarity: "fishing.rarity.uncommon",
                condition: "",
                image: "assets/media/item/fishing/key_uncommon.png",
            },
            {
                name: "fishing.cobweb",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.vanilla",
                condition: "",
                image: "assets/media/item/fishing/cobweb.png",
            },
            {
                name: "fishing.cactus",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.vanilla",
                condition: "",
                image: "assets/media/item/fishing/cactus.png",
            },
            {
                name: "fishing.stick",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.vanilla",
                condition: "",
                image: "assets/media/item/fishing/stick.png",
            },
            {
                name: "fishing.shulker_shell",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.vanilla",
                condition: "",
                image: "assets/media/item/fishing/shulker_shell.png",
            },
        ],
        canyon_shoal: [
            {
                name: "fishing.rare_treasure",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.rare",
                condition: "",
                image: "assets/media/item/fishing/treasure_rare.png",
            },
            {
                name: "fishing.rare_key",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.rare",
                condition: "",
                image: "assets/media/item/fishing/key_rare.png",
            },
            {
                name: "fishing.moray_eel",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.rare",
                condition: "",
                image: "assets/media/item/fishing/moray_eel.png",
            },
            {
                name: "fishing.carp",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.rare",
                condition: "",
                image: "assets/media/item/fishing/fish_carp.png",
            },
            {
                name: "fishing.humpback_chub",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.epic",
                condition: "",
                image: "assets/media/item/fishing/humpback_chub.png",
            },
            {
                name: "fishing.saw_fish",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.legendary",
                condition: "",
                image: "assets/media/item/fishing/sawfish.png",
            },
            {
                name: "fishing.razorback_sucker",
                level: 0,
                time: [""],
                rarity: "fishing.rarity.epic",
                condition: "",
                image: "assets/media/item/fishing/fish_razorback_sucker.png",
            },
        ],
    },
};
