/*
 * MBX, Community Based Project
 * Copyright (c) 2024 SiriusB_
 * SPDX-License-Identifier: MIT
 */

export interface FishInfo {
    name: string;
    level: number;
    time: ("Day" | "Night")[];
    rarity: "Vanilla" | "Common" | "Uncommon" | "Rare" | "Epic" | "Legendary";
    image?: string;
    condition?: string;
}

export const spotByMap: Record<string, string> = {
    spawn: "Tropical Shoal (Lvl 1)",
    kokoko: "Deep Shoal (Lvl 10)",
    quadra_plains: "Plain Shoal (Lvl 20)",
    bamboo_peak: "Bamboo Shoal (Lvl 30)",
    frostbite_fortress: "Cold Shoal (Lvl 60)",
    sandwhisper_dunes: "Desert Shoal (Lvl 40)",
};

export const fishData: Record<string, FishInfo[]> = {
    spawn: [
        {
            name: "Mandarinfish",
            level: 1,
            time: ["Day"],
            rarity: "Common",
            condition: "",
            image: "assets/media/item/fishing/mandarinfish.png",
        },
        {
            name: "Bone",
            level: 10,
            time: ["Day", "Night"],
            rarity: "Common",
            condition: "",
            image: "assets/media/item/fishing/bone.png",
        },
        {
            name: "Common Key",
            level: 10,
            time: ["Day", "Night"],
            rarity: "Common",
            condition: "storm",
            image: "assets/media/item/fishing/common_key.png",
        },
        {
            name: "Kraken",
            level: 10,
            time: ["Day", "Night"],
            rarity: "Uncommon",
            condition: "",
            image: "assets/media/item/fishing/kraken.png",
        },
        {
            name: "Breaded Fish",
            level: 1,
            time: ["Day", "Night"],
            rarity: "Common",
            condition: "",
            image: "assets/media/item/fishing/breaded_fish.png",
        },
        {
            name: "Pirate Crab",
            level: 1,
            time: ["Day", "Night"],
            rarity: "Uncommon",
            condition: "",
            image: "assets/media/item/fishing/pirate_crab.png",
        },
        {
            name: "Sea Salt",
            level: 10,
            time: ["Day", "Night"],
            rarity: "Uncommon",
            condition: "",
            image: "assets/media/item/fishing/sea_salt.png",
        },
        {
            name: "Cowrie Shell",
            level: 20,
            time: ["Day", "Night"],
            rarity: "Uncommon",
            condition: "",
            image: "assets/media/item/fishing/cowrie_shell.png",
        },
        {
            name: "Algae",
            level: 0,
            time: ["Day", "Night"],
            rarity: "Vanilla",
            condition: "",
            image: "assets/media/item/fishing/kelp.png",
        },
        {
            name: "Clam",
            level: 1,
            time: ["Day", "Night"],
            rarity: "Common",
            condition: "storm",
            image: "assets/media/item/fishing/clam.png",
        },
        {
            name: "Common Treasure",
            level: 0,
            time: ["Day"],
            rarity: "Common",
            condition: "",
            image: "assets/media/item/fishing/treasure_common.png",
        },
    ],
    kokoko: [
        {
            name: "Cowrie Shell",
            level: 20,
            time: ["Day", "Night"],
            rarity: "Uncommon",
            condition: "",
            image: "assets/media/item/fishing/cowrie_shell.png",
        },
        {
            name: "Pirate Crab",
            level: 1,
            time: ["Day", "Night"],
            rarity: "Uncommon",
            condition: "",
            image: "assets/media/item/fishing/pirate_crab.png",
        },
        {
            name: "Sea Salt",
            level: 10,
            time: ["Day", "Night"],
            rarity: "Uncommon",
            condition: "",
            image: "assets/media/item/fishing/sea_salt.png",
        },
        {
            name: "Green Ray",
            level: 10,
            time: ["Day", "Night"],
            rarity: "Uncommon",
            condition: "",
            image: "assets/media/item/fishing/green_ray.png",
        },
        {
            name: "Kraken",
            level: 10,
            time: ["Day", "Night"],
            rarity: "Uncommon",
            condition: "",
            image: "assets/media/item/fishing/kraken.png",
        },
        {
            name: "Moon Jellyfish",
            level: 0,
            time: ["Night"],
            rarity: "Uncommon",
            condition: "fullmoon",
            image: "assets/media/item/fishing/moon_jellyfish.png",
        },
        {
            name: "Clam",
            level: 1,
            time: ["Day", "Night"],
            rarity: "Common",
            condition: "rain",
            image: "assets/media/item/fishing/clam.png",
        },
        {
            name: "Common Key",
            level: 0,
            time: ["Day", "Night"],
            rarity: "Common",
            condition: "",
            image: "assets/media/item/fishing/common_key.png",
        },
        {
            name: "Common Treasure",
            level: 0,
            time: ["Day", "Night"],
            rarity: "Common",
            condition: "",
            image: "assets/media/item/fishing/treasure_common.png",
        },
        {
            name: "Algae",
            level: 0,
            time: ["Day", "Night"],
            rarity: "Vanilla",
            condition: "",
            image: "assets/media/item/fishing/kelp.png",
        },
        {
            name: "Ink Sac",
            level: 0,
            time: ["Day", "Night"],
            rarity: "Vanilla",
            condition: "",
            image: "assets/media/item/fishing/ink_sac.png",
        },
        {
            name: "Bone",
            level: 0,
            time: ["Day", "Night"],
            rarity: "Vanilla",
            condition: "",
            image: "assets/media/item/fishing/bone.png",
        },
    ],
    quadra_plains: [
        {
            name: "Ink Sac",
            level: 0,
            time: ["Day", "Night"],
            rarity: "Vanilla",
            condition: "",
            image: "assets/media/item/fishing/ink_sac.png",
        },
        {
            name: "Angelfish",
            level: 10,
            time: ["Day", "Night"],
            rarity: "Common",
            condition: "",
            image: "assets/media/item/fishing/angelfish.png",
        },
        {
            name: "Swordfish",
            level: 20,
            time: ["Day", "Night"],
            rarity: "Uncommon",
            condition: "",
            image: "assets/media/item/fishing/swordfish.png",
        },
        {
            name: "Wrasse",
            level: 50,
            time: ["Day", "Night"],
            rarity: "Rare",
            condition: "",
            image: "assets/media/item/fishing/wrasse.png",
        },
        {
            name: "Rainbow Trout",
            level: 10,
            time: ["Day", "Night"],
            rarity: "Rare",
            condition: "",
            image: "assets/media/item/fishing/rainbow_trout.png",
        },
        {
            name: "Bone",
            level: 0,
            time: ["Day", "Night"],
            rarity: "Vanilla",
            condition: "niceweather",
            image: "assets/media/item/fishing/bone.png",
        },
        {
            name: "Algae",
            level: 0,
            time: ["Night"],
            rarity: "Vanilla",
            condition: "",
            image: "assets/media/item/fishing/kelp.png",
        },
        {
            name: "Common Treasure",
            level: 0,
            time: ["Night"],
            rarity: "Common",
            condition: "",
            image: "assets/media/item/fishing/treasure_common.png",
        },
    ],
    bamboo_peak: [
        {
            name: "Parrotfish",
            level: 50,
            time: ["Day", "Night"],
            rarity: "Uncommon",
            condition: "",
            image: "assets/media/item/fishing/parrotfish.png",
        },
        {
            name: "Moorish Ido",
            level: 60,
            time: ["Day", "Night"],
            rarity: "Rare",
            condition: "",
            image: "assets/media/item/fishing/moorish_idol.png",
        },
        {
            name: "Monkfish",
            level: 60,
            time: ["Day", "Night"],
            rarity: "Epic",
            condition: "",
            image: "assets/media/item/fishing/monkfish.png",
        },
        {
            name: "Clownfish",
            level: 30,
            time: ["Day", "Night"],
            rarity: "Uncommon",
            condition: "",
            image: "assets/media/item/fishing/clownfish.png",
        },
        {
            name: "Sushi Crab",
            level: 80,
            time: ["Day"],
            rarity: "Legendary",
            condition: "",
            image: "assets/media/item/fishing/sushi_crab.png",
        },
        {
            name: "Surgeonfish",
            level: 30,
            time: ["Day", "Night"],
            rarity: "Rare",
            condition: "",
            image: "assets/media/item/fishing/surgeonfish.png",
        },
        {
            name: "Bamboo",
            level: 0,
            time: ["Day"],
            rarity: "Vanilla",
            condition: "",
            image: "assets/media/item/fishing/bamboo.png",
        },
        {
            name: "Poop",
            level: 1,
            time: ["Day"],
            rarity: "Rare",
            condition: "",
            image: "assets/media/item/fishing/poop.png",
        },
    ],
    sandwhisper_dunes: [
        {
            name: "Stick",
            level: 0,
            time: ["Day", "Night"],
            rarity: "Vanilla",
            condition: "",
            image: "assets/media/item/fishing/stick.png",
        },
        {
            name: "Cobweb",
            level: 0,
            time: ["Day", "Night"],
            rarity: "Vanilla",
            condition: "",
            image: "assets/media/item/fishing/cobweb.png",
        },
        {
            name: "Lionfish",
            level: 40,
            time: ["Day", "Night"],
            rarity: "Rare",
            condition: "",
            image: "assets/media/item/fishing/lionfish.png",
        },
        {
            name: "Triggerfish",
            level: 40,
            time: ["Day", "Night"],
            rarity: "Rare",
            condition: "",
            image: "assets/media/item/fishing/triggerfish.png",
        },
        {
            name: "Butterflyfish",
            level: 40,
            time: ["Day", "Night"],
            rarity: "Rare",
            condition: "",
            image: "assets/media/item/fishing/butterflyfish.png",
        },
        {
            name: "Cactus",
            level: 0,
            time: ["Day", "Night"],
            rarity: "Vanilla",
            condition: "",
            image: "assets/media/item/fishing/cactus_side.png",
        },
        {
            name: "Rainbow Sparkle Jelly",
            level: 90,
            time: ["Night"],
            rarity: "Legendary",
            condition: "rain",
            image: "assets/media/item/fishing/rainbow_sparkle_jelly.png",
        },
        {
            name: "Shulker Shell",
            level: 0,
            time: ["Night"],
            rarity: "Vanilla",
            condition: "",
            image: "assets/media/item/fishing/shulker_shell.png",
        },
    ],
    frostbite_fortress: [
        {
            name: "Golden Shrimp",
            level: 80,
            time: ["Night"],
            rarity: "Legendary",
            condition: "",
            image: "assets/media/item/fishing/golden_shrimp.png",
        },
        {
            name: "Shrimp",
            level: 60,
            time: ["Day", "Night"],
            rarity: "Epic",
            condition: "",
            image: "assets/media/item/fishing/shrimp.png",
        },
        {
            name: "Zander",
            level: 60,
            time: ["Day", "Night"],
            rarity: "Epic",
            condition: "",
            image: "assets/media/item/fishing/zander.png",
        },
        {
            name: "Sea Salt",
            level: 10,
            time: ["Day", "Night"],
            rarity: "Uncommon",
            condition: "",
            image: "assets/media/item/fishing/sea_salt.png",
        },
        {
            name: "Ice",
            level: 0,
            time: ["Day", "Night"],
            rarity: "Vanilla",
            condition: "",
            image: "assets/media/item/fishing/ice.png",
        },
        {
            name: "Snow Crab",
            level: 40,
            time: ["Day", "Night"],
            rarity: "Epic",
            condition: "",
            image: "assets/media/item/fishing/snow_crab.png",
        },
        {
            name: "Nether Star",
            level: 0,
            time: ["Night"],
            rarity: "Vanilla",
            condition: "fullmoon",
            image: "assets/media/item/fishing/nether_star.png",
        },
    ],
};
