/*
 * MBX, Community Based Project
 * Copyright (c) 2024 SiriusB_
 * SPDX-License-Identifier: MIT
 */

type FishRarity =
    | "fishing.rarity.vanilla"
    | "fishing.rarity.common"
    | "fishing.rarity.uncommon"
    | "fishing.rarity.rare"
    | "fishing.rarity.epic"
    | "fishing.rarity.legendary";

type FishTime =
    | "fishing.time.day"
    | "fishing.time.night"
    | "fishing.time.day_night";

export interface FishInfo {
    name: string;
    level: number;
    time: FishTime[];
    rarity: FishRarity;
    image?: string;
    condition?: string;
}

export const spotByMap: Record<string, string> = {
    spawn: "fishing.spot.spawn",
    kokoko: "fishing.spot.kokoko",
    quadra_plains: "fishing.spot.quadra_plains",
    bamboo_peak: "fishing.spot.bamboo_peak",
    frostbite_fortress: "fishing.spot.frostbite_fortress",
    sandwhisper_dunes: "fishing.spot.sandwhisper_dunes",
};

export const fishData: Record<string, FishInfo[]> = {
    spawn: [
        {
            name: "fishing.mandarinfish",
            level: 1,
            time: ["fishing.time.day"],
            rarity: "fishing.rarity.common",
            condition: "",
            image: "assets/media/item/fishing/mandarinfish.png",
        },
        {
            name: "fishing.bone",
            level: 10,
            time: ["fishing.time.day_night"],
            rarity: "fishing.rarity.common",
            condition: "",
            image: "assets/media/item/fishing/bone.png",
        },
        {
            name: "fishing.common_key",
            level: 10,
            time: ["fishing.time.day_night"],
            rarity: "fishing.rarity.common",
            condition: "storm",
            image: "assets/media/item/fishing/common_key.png",
        },
        {
            name: "fishing.kraken",
            level: 10,
            time: ["fishing.time.day_night"],
            rarity: "fishing.rarity.uncommon",
            condition: "",
            image: "assets/media/item/fishing/kraken.png",
        },
        {
            name: "fishing.breaded_fish",
            level: 1,
            time: ["fishing.time.day_night"],
            rarity: "fishing.rarity.common",
            condition: "",
            image: "assets/media/item/fishing/breaded_fish.png",
        },
        {
            name: "fishing.pirate_crab",
            level: 1,
            time: ["fishing.time.day_night"],
            rarity: "fishing.rarity.uncommon",
            condition: "",
            image: "assets/media/item/fishing/pirate_crab.png",
        },
        {
            name: "fishing.sea_salt",
            level: 10,
            time: ["fishing.time.day_night"],
            rarity: "fishing.rarity.uncommon",
            condition: "",
            image: "assets/media/item/fishing/sea_salt.png",
        },
        {
            name: "fishing.cowrie_shell",
            level: 20,
            time: ["fishing.time.day_night"],
            rarity: "fishing.rarity.uncommon",
            condition: "",
            image: "assets/media/item/fishing/cowrie_shell.png",
        },
        {
            name: "fishing.algae",
            level: 0,
            time: ["fishing.time.day_night"],
            rarity: "fishing.rarity.vanilla",
            condition: "",
            image: "assets/media/item/fishing/kelp.png",
        },
        {
            name: "fishing.clam",
            level: 1,
            time: ["fishing.time.day_night"],
            rarity: "fishing.rarity.common",
            condition: "storm",
            image: "assets/media/item/fishing/clam.png",
        },
        {
            name: "fishing.common_treasure",
            level: 0,
            time: ["fishing.time.day"],
            rarity: "fishing.rarity.common",
            condition: "",
            image: "assets/media/item/fishing/treasure_common.png",
        },
    ],
    kokoko: [
        {
            name: "fishing.cowrie_shell",
            level: 20,
            time: ["fishing.time.day_night"],
            rarity: "fishing.rarity.uncommon",
            condition: "",
            image: "assets/media/item/fishing/cowrie_shell.png",
        },
        {
            name: "fishing.pirate_crab",
            level: 1,
            time: ["fishing.time.day_night"],
            rarity: "fishing.rarity.uncommon",
            condition: "",
            image: "assets/media/item/fishing/pirate_crab.png",
        },
        {
            name: "fishing.sea_salt",
            level: 10,
            time: ["fishing.time.day_night"],
            rarity: "fishing.rarity.uncommon",
            condition: "",
            image: "assets/media/item/fishing/sea_salt.png",
        },
        {
            name: "fishing.green_ray",
            level: 10,
            time: ["fishing.time.day_night"],
            rarity: "fishing.rarity.uncommon",
            condition: "",
            image: "assets/media/item/fishing/green_ray.png",
        },
        {
            name: "fishing.kraken",
            level: 10,
            time: ["fishing.time.day_night"],
            rarity: "fishing.rarity.uncommon",
            condition: "",
            image: "assets/media/item/fishing/kraken.png",
        },
        {
            name: "fishing.moon_jellyfish",
            level: 0,
            time: ["fishing.time.night"],
            rarity: "fishing.rarity.uncommon",
            condition: "fullmoon",
            image: "assets/media/item/fishing/moon_jellyfish.png",
        },
        {
            name: "fishing.clam",
            level: 1,
            time: ["fishing.time.day_night"],
            rarity: "fishing.rarity.common",
            condition: "rain",
            image: "assets/media/item/fishing/clam.png",
        },
        {
            name: "fishing.common_key",
            level: 0,
            time: ["fishing.time.day_night"],
            rarity: "fishing.rarity.common",
            condition: "",
            image: "assets/media/item/fishing/common_key.png",
        },
        {
            name: "fishing.common_treasure",
            level: 0,
            time: ["fishing.time.day_night"],
            rarity: "fishing.rarity.common",
            condition: "",
            image: "assets/media/item/fishing/treasure_common.png",
        },
        {
            name: "fishing.algae",
            level: 0,
            time: ["fishing.time.day_night"],
            rarity: "fishing.rarity.vanilla",
            condition: "",
            image: "assets/media/item/fishing/kelp.png",
        },
        {
            name: "fishing.ink_sac",
            level: 0,
            time: ["fishing.time.day_night"],
            rarity: "fishing.rarity.vanilla",
            condition: "",
            image: "assets/media/item/fishing/ink_sac.png",
        },
        {
            name: "fishing.bone",
            level: 0,
            time: ["fishing.time.day_night"],
            rarity: "fishing.rarity.vanilla",
            condition: "",
            image: "assets/media/item/fishing/bone.png",
        },
    ],
    quadra_plains: [
        {
            name: "fishing.ink_sac",
            level: 0,
            time: ["fishing.time.day_night"],
            rarity: "fishing.rarity.vanilla",
            condition: "",
            image: "assets/media/item/fishing/ink_sac.png",
        },
        {
            name: "fishing.angelfish",
            level: 10,
            time: ["fishing.time.day_night"],
            rarity: "fishing.rarity.common",
            condition: "",
            image: "assets/media/item/fishing/angelfish.png",
        },
        {
            name: "fishing.swordfish",
            level: 20,
            time: ["fishing.time.day_night"],
            rarity: "fishing.rarity.uncommon",
            condition: "",
            image: "assets/media/item/fishing/swordfish.png",
        },
        {
            name: "fishing.wrasse",
            level: 50,
            time: ["fishing.time.day_night"],
            rarity: "fishing.rarity.rare",
            condition: "",
            image: "assets/media/item/fishing/wrasse.png",
        },
        {
            name: "fishing.rainbow_trout",
            level: 10,
            time: ["fishing.time.day_night"],
            rarity: "fishing.rarity.rare",
            condition: "",
            image: "assets/media/item/fishing/rainbow_trout.png",
        },
        {
            name: "fishing.bone",
            level: 0,
            time: ["fishing.time.day_night"],
            rarity: "fishing.rarity.vanilla",
            condition: "niceweather",
            image: "assets/media/item/fishing/bone.png",
        },
        {
            name: "fishing.algae",
            level: 0,
            time: ["fishing.time.night"],
            rarity: "fishing.rarity.vanilla",
            condition: "",
            image: "assets/media/item/fishing/kelp.png",
        },
        {
            name: "fishing.common_treasure",
            level: 0,
            time: ["fishing.time.night"],
            rarity: "fishing.rarity.common",
            condition: "",
            image: "assets/media/item/fishing/treasure_common.png",
        },
    ],
    bamboo_peak: [
        {
            name: "fishing.parrotfish",
            level: 50,
            time: ["fishing.time.day_night"],
            rarity: "fishing.rarity.uncommon",
            condition: "",
            image: "assets/media/item/fishing/parrotfish.png",
        },
        {
            name: "fishing.moorish_idol",
            level: 60,
            time: ["fishing.time.day_night"],
            rarity: "fishing.rarity.rare",
            condition: "",
            image: "assets/media/item/fishing/moorish_idol.png",
        },
        {
            name: "fishing.monkfish",
            level: 60,
            time: ["fishing.time.day_night"],
            rarity: "fishing.rarity.epic",
            condition: "",
            image: "assets/media/item/fishing/monkfish.png",
        },
        {
            name: "fishing.clownfish",
            level: 30,
            time: ["fishing.time.day_night"],
            rarity: "fishing.rarity.uncommon",
            condition: "",
            image: "assets/media/item/fishing/clownfish.png",
        },
        {
            name: "fishing.sushi_crab",
            level: 80,
            time: ["fishing.time.day"],
            rarity: "fishing.rarity.legendary",
            condition: "",
            image: "assets/media/item/fishing/sushi_crab.png",
        },
        {
            name: "fishing.surgeonfish",
            level: 30,
            time: ["fishing.time.day_night"],
            rarity: "fishing.rarity.rare",
            condition: "",
            image: "assets/media/item/fishing/surgeonfish.png",
        },
        {
            name: "fishing.bamboo",
            level: 0,
            time: ["fishing.time.day"],
            rarity: "fishing.rarity.vanilla",
            condition: "",
            image: "assets/media/item/fishing/bamboo.png",
        },
        {
            name: "fishing.poop",
            level: 1,
            time: ["fishing.time.day"],
            rarity: "fishing.rarity.rare",
            condition: "",
            image: "assets/media/item/fishing/poop.png",
        },
    ],
    sandwhisper_dunes: [
        {
            name: "fishing.stick",
            level: 0,
            time: ["fishing.time.day_night"],
            rarity: "fishing.rarity.vanilla",
            condition: "",
            image: "assets/media/item/fishing/stick.png",
        },
        {
            name: "fishing.cobweb",
            level: 0,
            time: ["fishing.time.day_night"],
            rarity: "fishing.rarity.vanilla",
            condition: "",
            image: "assets/media/item/fishing/cobweb.png",
        },
        {
            name: "fishing.lionfish",
            level: 40,
            time: ["fishing.time.day_night"],
            rarity: "fishing.rarity.rare",
            condition: "",
            image: "assets/media/item/fishing/lionfish.png",
        },
        {
            name: "fishing.triggerfish",
            level: 40,
            time: ["fishing.time.day_night"],
            rarity: "fishing.rarity.rare",
            condition: "",
            image: "assets/media/item/fishing/triggerfish.png",
        },
        {
            name: "fishing.butterflyfish",
            level: 40,
            time: ["fishing.time.day_night"],
            rarity: "fishing.rarity.rare",
            condition: "",
            image: "assets/media/item/fishing/butterflyfish.png",
        },
        {
            name: "fishing.cactus",
            level: 0,
            time: ["fishing.time.day_night"],
            rarity: "fishing.rarity.vanilla",
            condition: "",
            image: "assets/media/item/fishing/cactus_side.png",
        },
        {
            name: "fishing.rainbow_sparkle_jelly",
            level: 90,
            time: ["fishing.time.night"],
            rarity: "fishing.rarity.legendary",
            condition: "rain",
            image: "assets/media/item/fishing/rainbow_sparkle_jelly.png",
        },
        {
            name: "fishing.shulker_shell",
            level: 0,
            time: ["fishing.time.night"],
            rarity: "fishing.rarity.vanilla",
            condition: "",
            image: "assets/media/item/fishing/shulker_shell.png",
        },
    ],
    frostbite_fortress: [
        {
            name: "fishing.golden_shrimp",
            level: 80,
            time: ["fishing.time.night"],
            rarity: "fishing.rarity.legendary",
            condition: "",
            image: "assets/media/item/fishing/golden_shrimp.png",
        },
        {
            name: "fishing.shrimp",
            level: 60,
            time: ["fishing.time.day_night"],
            rarity: "fishing.rarity.epic",
            condition: "",
            image: "assets/media/item/fishing/shrimp.png",
        },
        {
            name: "fishing.zander",
            level: 60,
            time: ["fishing.time.day_night"],
            rarity: "fishing.rarity.epic",
            condition: "",
            image: "assets/media/item/fishing/zander.png",
        },
        {
            name: "fishing.sea_salt",
            level: 10,
            time: ["fishing.time.day_night"],
            rarity: "fishing.rarity.uncommon",
            condition: "",
            image: "assets/media/item/fishing/sea_salt.png",
        },
        {
            name: "fishing.ice",
            level: 0,
            time: ["fishing.time.day_night"],
            rarity: "fishing.rarity.vanilla",
            condition: "",
            image: "assets/media/item/fishing/ice.png",
        },
        {
            name: "fishing.snow_crab",
            level: 40,
            time: ["fishing.time.day_night"],
            rarity: "fishing.rarity.epic",
            condition: "",
            image: "assets/media/item/fishing/snow_crab.png",
        },
        {
            name: "fishing.nether_star",
            level: 0,
            time: ["fishing.time.night"],
            rarity: "fishing.rarity.vanilla",
            condition: "fullmoon",
            image: "assets/media/item/fishing/nether_star.png",
        },
    ],
};
