# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: MBXCommunity CI/CD

on:
    push:
        branches: [deploy]

jobs:
    build:
        runs-on: self-hosted

        strategy:
            matrix:
                node-version: [22.x]

        steps:
            - uses: actions/checkout@v4

            - name: Load Bun PATH
              run: source ~/.bashrc

            - name: Check Bun installation
              run: |
                  echo "Using Bun version:"
                  ~/.bun/bin/bun --version

            - name: Install dependencies
              run: ~/.bun/bin/bun install

            - name: Run tests
              run: ~/.bun/bin/bun test

            - name: Build project
              run: ~/.bun/bin/bun run build

            # Deploying the build to /var/www/mbxcommunity
            - name: Deploy to /var/www/mbxcommunity
              run: |
                  sudo rm -rf /var/www/mbxcommunity/*
                  sudo cp -R dist/* /var/www/mbxcommunity
